### ISSUE TITLE
Make links sent in discord work as links in minecraft

### ISSUE THREAD

**Issue by neijrr** [Erdragh/AstralBot#19]
Simple QoL change to make it so people don't have to open discord to open links

**Comment by Erdragh** [comment]
Sounds like a simple change but isn't actually that trivial. It's something I want to do, but I'll have to look into the discord api some more about how to get a formatted message instead of just the raw content.

**Comment by Erdragh** [comment]
I'm now parsing Discord messages as Markdown and converting them into Minecraft's Chat Component system with a renderer that uses [Commonmark](https://github.com/commonmark/commonmark-java) for parsing. It's not final yet, as I want to add more configurability, but the topic of this issue, making links work as links in Minecraft, is implemented.

See #21 for more info.
